name: tylerstuff
favicon: null
layout_spectrum: 0.32051
typography_spectrum: 0.689229367300868
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
